# Set-up

In [13]:
import pandas as pd
import numpy as np
import os
import datetime

os.chdir(r"C:\Users\karud\Documents\Putnam\data")
partnerships = pd.read_csv(r"partnership_map.csv")
touchpoints = pd.read_csv(r"touchpoints.csv")
trades = pd.read_csv(r"trades.csv")

In [14]:
pd.set_option('display.max_columns', None)

# Explore Partners
- In partners_full, see that there are 50 partnership groups among 99 individuals and 500 interactions overall

### Create dataframe (partnerships_full) with one row per Individual ID

- Step 1: Make a list for each row in the dataframe that literally reads the entire INDIVIDUAL_IDS column
- Step 2: Add the PARTNERSHIP_ID as another column
- Step 3: Append to the partnership_full dataframe

In [15]:
import ast
partnerships_full= pd.DataFrame(columns = ['INDIVIDUAL_ID', 'PARTNERSHIP_ID'])

# Iterate over each row 
for index, rows in partnerships.iterrows():
    # make list
    list_ind_ids = rows.INDIVIDUAL_IDS
    list_ind_ids = ast.literal_eval(list_ind_ids)
    # make dataframe
    df_ind_ids = pd.DataFrame(list_ind_ids, columns =['INDIVIDUAL_ID'])
    # add column for the partnership ID
    df_ind_ids['PARTNERSHIP_ID'] = rows.PARTNERSHIP_ID
    # append to partnership_full
    partnerships_full = partnerships_full.append(df_ind_ids)

In [16]:
partnerships_full.head(100)

   INDIVIDUAL_ID PARTNERSHIP_ID
0     AYGKZW5YPG     IH9D7QU0SW
1     UDSS4B9P65     IH9D7QU0SW
0     701CU2R5WE     RAO5TAG1BD
1     C3FC972N4Q     RAO5TAG1BD
0     QXNWJE6H5G     T9AD15KSTV
1     086N3Y4VVM     T9AD15KSTV
0     C9NRGXF7IO     N3GUJVQNZ8
1     K3M3GSSAN2     N3GUJVQNZ8
0     4CQTUTNULG     TN2QK2P9RS
1     TPJKXTM0CB     TN2QK2P9RS
0     TPJKXTM0CB     6RUCM9BPJ9
1     4L0Q61KPQL     6RUCM9BPJ9
0     JMT28B228R     AHTDNYP4A3
1     NOFRPS4Q9T     AHTDNYP4A3
0     827HZMYB0T     20B9HH7W8T
1     17PCTFAZUP     20B9HH7W8T
0     FO8YWV23ZK     ZW0J9NZAS3
1     ARN5GMCI89     ZW0J9NZAS3
0     4L0Q61KPQL     ZQ5C5X1DWI
1     D2XB6WSA2C     ZQ5C5X1DWI
0     H9NSEIPUYE     J7GOCJMT4X
1     701CU2R5WE     J7GOCJMT4X
0     2MVH9N44OT     EQF1X3CNKZ
1     QH6U83FHKN     EQF1X3CNKZ
0     YH7NSGYL1V     7VBKY5B1PM
1     701CU2R5WE     7VBKY5B1PM
0     UBRJS7UAWJ     A1Y388YRKE
1     PO2L3AEFED     A1Y388YRKE
0     JMT28B228R     2WTR20XDSA
1     SXS9F6CSY1     2WTR20XDSA
..           ...            ...
0     SKBPNEDBQS     H3EALASYBT
1     ARN5GMCI89     H3EALASYBT
2     TXW929QG7V     H3EALASYBT
3     AM03D1XUAP     H3EALASYBT
4     QH6U83FHKN     H3EALASYBT
5     QXNWJE6H5G     H3EALASYBT
6     4NI2BAS5NY     H3EALASYBT
7     C9NRGXF7IO     H3EALASYBT
8     2MVH9N44OT     H3EALASYBT
9     NTEGEVCM9X     H3EALASYBT
0     A06WP1H62W     9KPSVHG8YA
1     W1Y175DVPO     9KPSVHG8YA
2     RG0G1D96G3     9KPSVHG8YA
3     4ODNGNJKKP     9KPSVHG8YA
4     K3M3GSSAN2     9KPSVHG8YA
5     UYPHDND4FA     9KPSVHG8YA
6     0ESA3CXA5N     9KPSVHG8YA
7     UI7EJIY2KI     9KPSVHG8YA
8     ZK6QSE5CWV     9KPSVHG8YA
9     2MVH9N44OT     9KPSVHG8YA
0     4KWW1KR3JY     59YB0GWAEV
1     Z3X0LBABH7     59YB0GWAEV
2     FO8YWV23ZK     59YB0GWAEV
3     W1Y175DVPO     59YB0GWAEV
4     Q16YO4JCU6     59YB0GWAEV
5     2F99RMVRIZ     59YB0GWAEV
6     13Y2YC97H6     59YB0GWAEV
7     UBRJS7UAWJ     59YB0GWAEV
8     701CU2R5WE     59YB0GWAEV
9     DBYS4P30SU     59YB0GWAEV

[100 rows x 2 columns]

## Make dataframe with number of partnerships per individual

In [17]:
group_p = partnerships_full.groupby(['INDIVIDUAL_ID']).agg({'PARTNERSHIP_ID' : ["count"]})
group_p.columns = ['NUM_PARTNERSHIPS']
group_p = group_p.reset_index()
group_p=group_p.rename(columns={'INDIVIDUAL_ID': 'ID'})
group_p.head()

           ID  NUM_PARTNERSHIPS
0  007AS3ESRJ                 2
1  086N3Y4VVM                 6
2  0ESA3CXA5N                 7
3  0FIT0NJYNV                 6
4  13Y2YC97H6                 4

## Make dataframe with number of individuals in a partnership

In [18]:
group_i = partnerships_full.groupby(['PARTNERSHIP_ID']).agg({'INDIVIDUAL_ID' : ["count"]})
group_i.columns = ['NUM_ADVISORS']
group_i = group_i.reset_index()
group_i=group_i.rename(columns={'PARTNERSHIP_ID': 'ID'})
group_i.head()

           ID  NUM_ADVISORS
0  08JLESLKWL            20
1  0WVM3IMR53            20
2  1U7UBFTOIE            20
3  20B9HH7W8T             2
4  2J1CGBDXSV            20

# Explore Touchpoints

- Covers 365 days a year and each individual has different amount of touchpoints
- Total days range 1 to 100 for each advisor
- 5,006 total touchpoints throughout the year
- Touchpoints are documented on each day a touch point happened. Different people can have a different date range
- Each row is the number of touch points on that day

Touchpoints dataset keeps track of engagement history with each individual advisor.

Columns are:

- DATE: date of touchpoints
- ID: individual identifier
- EMAIL_SENT: total number of emails sent
 - Data entry error: 41% of observations have EMAIL_SENT > EMAIL_OPENED
- EMAIL_OPENED: total number of emails opened
- IN_PERSON_MEETING: total number of in person meeting
- PHONE_ATTEMPT: total number of phone calls HOLA made to advisors (unanswered)
- PHONE_SUCCESS: total number of phone calls answered by advisors
- WEBINAR: total number of webinar advisors go to
- MAIL: total number of mailssent to an advisor

In [19]:
touchpoints.head(10)

,DATE,ID,EMAIL_SENT,EMAIL_OPENED,IN_PERSON_MEETING,PHONE_ATTEMPT,PHONE_SUCCESS,WEBINAR,MAIL
0,01/18/2018,RBD08MZXX1,19,11,3,2,1,19,2
1,10/19/2018,RBD08MZXX1,32,25,1,1,1,68,1
2,12/22/2018,RBD08MZXX1,18,14,4,1,1,19,2
3,03/11/2018,RBD08MZXX1,19,9,2,1,0,55,0
4,09/04/2018,RBD08MZXX1,34,33,4,3,2,28,2
5,06/29/2018,RBD08MZXX1,37,11,2,1,0,62,0
6,07/04/2018,RBD08MZXX1,24,19,3,1,2,16,1
7,03/23/2018,RBD08MZXX1,24,10,1,1,2,24,2
8,08/14/2018,RBD08MZXX1,24,8,0,1,0,69,1
9,09/17/2018,RBD08MZXX1,15,17,0,1,0,39,0

In [20]:
# convert DATE from object to datetime

touchpoints = touchpoints.apply(lambda col: pd.to_datetime(col, errors='ignore')
             if col.dtypes==object
              else col,
              axis=0)

touchpoints['MONTH'] = pd.DatetimeIndex(touchpoints['DATE']).month

# Explore Trades

Trades dataset hastransaction history for each trade that has been made by an entity. An
entity can be an individual advisor or partnerships. Advisors work for external firms and
partnerships are formed on the free will of advisors within the same company or across
companies.

Columns of this dataset include:

- ID: id of trading entity, unique identifier for an entity
- FIRM_NAME: name of the firm each individual advisor worksfor
- ELITE_FIRM: a flag indicating if the firm is an industry elite firm
- TRADE_TYPE: a flag indicating if the transaction is made by an individual or partnership
 - if TRADE_TYPE = P, then the partnership is in the Partners df
- TRAN_ID: transaction id, unique identifier for a transaction
- TRAN_DATE: datetime of each transaction that has been made
- TRAN_AMT: monetary amount for each transaction
 - 16% of entries have negative TRAN_AMT: could be either redemption or trades reversals
- PROD_ID: id of the product for each transaction, unique identifier for a product

In [21]:
trades.head(10)

,ID,FIRM_NAME,ELITE_FIRM,TRADE_TYPE,TRAN_ID,TRAN_DATE,PROD_ID,TRAN_AMT
0,SCQ0XCQ7O1,Firm L,YES,I,24410485,2018-06-30 00:27:00,1017,8750.439154
1,5KO6XTG3NZ,Firm H,NaN,I,66379628,2018-12-22 07:44:00,4233,5932.776580
2,UDSS4B9P65,Firm G,YES,I,66146891,2018-02-03 18:05:00,1017,13161.501280
3,UDSS4B9P65,Firm G,YES,I,59545643,2018-07-29 19:07:00,1017,4401.004771
4,AHTDNYP4A3,NaN,NaN,P,34620126,2018-03-13 21:18:00,1972,5357.264141
5,B79TELFZL7,Firm J,NaN,I,44912672,2018-05-07 02:55:10,1017,7930.119997
6,GKKCWNOKZ0,Firm G,YES,I,10074884,2018-11-27 21:21:00,1017,16682.917878
7,U3TBS57JJ5,NaN,NaN,P,70245581,2018-02-13 15:11:00,1017,9140.030474
8,A4J0YU0L11,Firm J,NaN,I,88147718,2018-07-28 07:01:00,4330,78863.337745
9,DF49LAD02I,Firm L,YES,I,35942754,2018-07-12 23:44:00,2183,49503.032184

In [22]:
# convert from object to datetime
trades = trades.apply(lambda col: pd.to_datetime(col, errors='ignore')
             if col.dtypes==object
              else col,
              axis=0)

# Now to add yearly information

In [24]:
# first by TRAN_ID

group_tran_id = trades.groupby(['ID']).agg({'TRAN_ID' : ["count"]})
group_tran_id.columns = ['TRAN_COUNT']
group_tran_id = group_tran_id.reset_index()
group_tran_id.head()

# next by TRAN_AMT

group_tran = trades.groupby(['ID']).agg({'TRAN_AMT' : ["sum", "median","min","max"]})
group_tran.columns = ['TRAN_AMT_TOTAL', 'TRAN_AMT_MEDIAN', 'TRAN_AMT_MIN', 'TRAN_AMT_MAX']
group_tran = group_tran.reset_index()
group_tran.head()

# next by PROD_ID

group_prod = trades.groupby(['ID']).agg({'PROD_ID' : ["count", "nunique"]})
group_prod.columns = ['PROD_TOTAL', 'PROD_UNIQUE']
group_prod = group_prod.reset_index()
group_prod.head()

# next, we will use the dummy variables per transaction and aggregate to yearly

prod_hot = pd.get_dummies(trades, columns = ['PROD_ID'])

prod_hot_mo = prod_hot.groupby(['ID']).agg({'PROD_ID_1017': ["sum"], 'PROD_ID_1051': ["sum"], 'PROD_ID_1246': ["sum"],
       'PROD_ID_1549': ["sum"], 'PROD_ID_1972': ["sum"], 'PROD_ID_2183': ["sum"], 'PROD_ID_2439': ["sum"],
       'PROD_ID_2837': ["sum"], 'PROD_ID_2892': ["sum"], 'PROD_ID_4215': ["sum"], 'PROD_ID_4233': ["sum"],
       'PROD_ID_4252': ["sum"], 'PROD_ID_4330': ["sum"], 'PROD_ID_5280': ["sum"], 'PROD_ID_6099': ["sum"],
       'PROD_ID_6168': ["sum"], 'PROD_ID_7341': ["sum"], 'PROD_ID_7455': ["sum"], 'PROD_ID_9667' : ["sum"]})

prod_hot_mo.columns = ['PROD_ID_1017', 'PROD_ID_1051', 'PROD_ID_1246',
       'PROD_ID_1549', 'PROD_ID_1972', 'PROD_ID_2183', 'PROD_ID_2439',
       'PROD_ID_2837', 'PROD_ID_2892', 'PROD_ID_4215', 'PROD_ID_4233',
       'PROD_ID_4252', 'PROD_ID_4330', 'PROD_ID_5280', 'PROD_ID_6099',
       'PROD_ID_6168', 'PROD_ID_7341', 'PROD_ID_7455', 'PROD_ID_9667']

prod_hot_mo = prod_hot_mo.reset_index()

# create dataframe of summary info for each advisor

trades_summary = trades[['ID','FIRM_NAME', 'ELITE_FIRM', 'TRADE_TYPE']]

# create list of all the dataframes to merge 
data_frames = [group_tran_id, group_tran, group_prod, prod_hot_mo]

from functools import reduce

df_merged = reduce(lambda left, right: pd.merge(left, right,on=['ID'],
                                                   how='outer'), data_frames)

# next, add the summary information

df_merged_all = pd.merge(df_merged, trades_summary, on = ['ID'], how="outer")
df_merged_all = df_merged_all.drop_duplicates()

In [25]:

# now add the number of partnerships or individuals depending on group type

df_merged_all1 = pd.merge(df_merged_all, group_i, on = ['ID'], how = 'left')
df_merged_all2 = pd.merge(df_merged_all1, group_p, on = ['ID'], how = 'left')

# now to replace NaN for NUM_PARTNERSHIPS with 0 and NaN for NUM_ADVISORS with 1

df_merged_all2['NUM_PARTNERSHIPS']= df_merged_all2['NUM_PARTNERSHIPS'].fillna(0)
df_merged_all2['NUM_ADVISORS']= df_merged_all2['NUM_ADVISORS'].fillna(1)
df_merged_all2.head()

,ID,TRAN_COUNT,TRAN_AMT_TOTAL,TRAN_AMT_MEDIAN,TRAN_AMT_MIN,TRAN_AMT_MAX,PROD_TOTAL,PROD_UNIQUE,PROD_ID_1017,PROD_ID_1051,PROD_ID_1246,PROD_ID_1549,PROD_ID_1972,PROD_ID_2183,PROD_ID_2439,PROD_ID_2837,PROD_ID_2892,PROD_ID_4215,PROD_ID_4233,PROD_ID_4252,PROD_ID_4330,PROD_ID_5280,PROD_ID_6099,PROD_ID_6168,PROD_ID_7341,PROD_ID_7455,PROD_ID_9667,FIRM_NAME,ELITE_FIRM,TRADE_TYPE,NUM_ADVISORS,NUM_PARTNERSHIPS
0,007AS3ESRJ,91,604939.113793,9899.789234,-17551.618139,20076.667598,91,15,27,0,0,3,6,6,1,4,1,0,0,6,7,9,2,3,3,6,7,Firm J,NaN,I,1.0,2.0
1,086N3Y4VVM,76,517327.589957,8810.902491,-19614.976870,21702.895016,76,15,29,0,0,2,4,2,6,3,1,0,0,2,7,3,4,3,4,3,3,Firm L,YES,I,1.0,6.0
2,08JLESLKWL,117,746599.114749,8287.429962,-20318.569863,20318.569863,117,17,35,1,0,8,4,0,9,9,3,1,4,2,8,3,7,6,2,2,13,NaN,NaN,P,20.0,0.0
3,0ESA3CXA5N,10,61539.512794,10167.483504,-15392.714725,15392.714725,10,5,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,4,1,1,0,Firm J,NaN,I,1.0,7.0
4,0FIT0NJYNV,72,462249.906811,7619.226435,-13249.798248,21905.876796,72,16,26,2,0,4,5,5,4,7,0,1,0,1,2,1,1,3,1,2,7,Firm B,NaN,I,1.0,6.0

In [26]:
df_merged_all2.head(200)

,ID,TRAN_COUNT,TRAN_AMT_TOTAL,TRAN_AMT_MEDIAN,TRAN_AMT_MIN,TRAN_AMT_MAX,PROD_TOTAL,PROD_UNIQUE,PROD_ID_1017,PROD_ID_1051,PROD_ID_1246,PROD_ID_1549,PROD_ID_1972,PROD_ID_2183,PROD_ID_2439,PROD_ID_2837,PROD_ID_2892,PROD_ID_4215,PROD_ID_4233,PROD_ID_4252,PROD_ID_4330,PROD_ID_5280,PROD_ID_6099,PROD_ID_6168,PROD_ID_7341,PROD_ID_7455,PROD_ID_9667,FIRM_NAME,ELITE_FIRM,TRADE_TYPE,NUM_ADVISORS,NUM_PARTNERSHIPS
0,007AS3ESRJ,91,6.049391e+05,9.899789e+03,-1.755162e+04,2.007667e+04,91,15,27,0,0,3,6,6,1,4,1,0,0,6,7,9,2,3,3,6,7,Firm J,NaN,I,1.0,2.0
1,086N3Y4VVM,76,5.173276e+05,8.810902e+03,-1.961498e+04,2.170290e+04,76,15,29,0,0,2,4,2,6,3,1,0,0,2,7,3,4,3,4,3,3,Firm L,YES,I,1.0,6.0
2,08JLESLKWL,117,7.465991e+05,8.287430e+03,-2.031857e+04,2.031857e+04,117,17,35,1,0,8,4,0,9,9,3,1,4,2,8,3,7,6,2,2,13,NaN,NaN,P,20.0,0.0
3,0ESA3CXA5N,10,6.153951e+04,1.016748e+04,-1.539271e+04,1.539271e+04,10,5,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,4,1,1,0,Firm J,NaN,I,1.0,7.0
4,0FIT0NJYNV,72,4.622499e+05,7.619226e+03,-1.324980e+04,2.190588e+04,72,16,26,2,0,4,5,5,4,7,0,1,0,1,2,1,1,3,1,2,7,Firm B,NaN,I,1.0,6.0
5,0WVM3IMR53,27,1.617615e+05,7.506850e+03,-1.806305e+04,1.840747e+04,27,10,8,0,0,3,0,0,3,2,0,0,0,1,3,0,3,0,1,1,2,NaN,NaN,P,20.0,0.0
6,13Y2YC97H6,26,3.773794e+06,1.469734e+05,-4.845686e+04,3.154992e+05,26,10,14,0,1,1,2,0,0,0,0,0,0,2,1,0,1,1,1,0,2,Firm L,YES,I,1.0,4.0
7,166FJV65R6,34,2.088708e+05,7.655650e+03,-2.016292e+04,2.016292e+04,34,10,19,0,0,1,1,0,0,1,3,0,1,0,1,1,0,5,0,1,0,Firm C,NaN,I,1.0,4.0
8,17PCTFAZUP,106,7.338428e+05,7.836283e+03,-2.018793e+04,2.587249e+04,106,14,28,0,1,3,3,10,10,8,0,0,0,9,11,5,3,9,0,1,5,Firm K,NaN,I,1.0,2.0
9,1U7UBFTOIE,45,3.934622e+05,1.006208e+04,-1.313440e+04,2.768427e+04,45,12,21,0,0,1,1,1,2,1,0,0,1,4,4,1,0,4,0,0,4,NaN,NaN,P,20.0,0.0
10,1ZEAIO3U5N,33,3.242318e+06,1.107641e+05,-7.961543e+04,2.792076e+05,33,12,11,0,0,4,0,1,2,2,2,0,0,0,2,2,0,2,2,1,2,Firm J,NaN,I,1.0,2.0
11,20B9HH7W8T,124,1.021609e+06,9.825066e+03,-1.972889e+04,2.289901e+04,124,17,49,1,0,4,3,3,3,10,2,6,0,5,12,3,3,4,1,5,10,NaN,NaN,P,2.0,0.0
12,2A9X4KHXZI,122,9.758739e+05,8.799446e+03,-1.844995e+04,2.656341e+04,122,17,37,2,0,7,3,5,2,9,4,0,3,5,14,3,2,11,5,2,8,Firm C,NaN,I,1.0,5.0
13,2F99RMVRIZ,26,2.078204e+05,9.594821e+03,-1.180927e+04,1.736468e+04,26,8,10,0,0,1,1,1,0,6,0,0,0,0,5,0,0,0,0,1,1,Firm G,YES,I,1.0,4.0
14,2J1CGBDXSV,36,2.378138e+05,9.799270e+03,-2.248079e+04,2.248079e+04,36,9,12,0,0,0,0,3,6,0,0,0,0,3,2,2,3,4,0,0,1,NaN,NaN,P,20.0,0.0
15,2MVH9N44OT,73,5.888982e+05,9.516012e+03,-1.280890e+04,2.289887e+04,73,13,26,1,0,0,5,3,3,9,0,2,0,6,3,0,2,11,0,1,1,Firm I,NaN,I,1.0,10.0
16,2WTR20XDSA,44,2.557327e+05,7.966589e+03,-1.778489e+04,1.778489e+04,44,10,21,0,0,1,0,0,1,3,0,0,1,4,7,0,0,4,0,1,1,NaN,NaN,P,2.0,0.0
17,3B7BHD6UEU,43,2.710111e+05,8.134993e+03,-1.456792e+04,2.107853e+04,43,6,27,0,0,3,0,0,4,3,0,0,0,0,2,0,0,0,0,0,4,Firm L,YES,I,1.0,1.0
18,3CN0CG38T5,77,5.395165e+05,8.816165e+03,-1.573848e+04,2.192931e+04,77,14,30,0,0,2,1,1,1,7,0,0,1,1,18,4,1,1,2,0,7,Firm L,YES,I,1.0,6.0
19,3IZHN85PK8,31,1.994069e+05,6.883335e+03,-1.528689e+04,1.691683e+04,31,12,13,0,0,3,1,0,0,1,1,0,1,0,2,1,2,0,1,1,4,Firm J,NaN,I,1.0,5.0
20,3XO893HUB7,168,1.038258e+06,8.346151e+03,-1.694156e+04,1.922991e+04,168,17,45,6,2,4,1,9,9,11,0,0,11,11,5,4,2,8,6,8,26,Firm A,NaN,I,1.0,5.0
21,3Y1K6KE4BT,16,1.055152e+05,8.992678e+03,-1.112624e+04,1.395531e+04,16,7,4,0,0,3,0,1,2,0,0,0,0,2,1,0,0,0,0,0,3,NaN,NaN,P,10.0,0.0
22,4CQTUTNULG,29,2.481045e+05,8.339429e+03,-1.027390e+04,2.257754e+04,29,7,15,0,0,0,0,0,4,2,0,0,0,0,5,0,1,0,1,0,1,Firm C,NaN,I,1.0,4.0
23,4KWW1KR3JY,99,6.642332e+05,8.447328e+03,-1.836678e+04,2.002703e+04,99,15,26,1,0,5,9,5,0,9,0,0,1,2,8,3,3,4,4,6,13,Firm L,YES,I,1.0,4.0
24,4L0Q61KPQL,101,7.522734e+05,9.451739e+03,-1.501825e+04,1.998238e+04,101,16,48,1,0,1,3,6,4,6,3,2,1,9,4,4,3,0,1,0,5,Firm E,NaN,I,1.0,6.0
25,4NI2BAS5NY,32,2.451686e+05,7.820176e+03,-1.321963e+04,1.604043e+04,32,13,7,0,3,0,1,0,1,1,0,0,1,3,7,1,2,1,0,3,1,Firm E,NaN,I,1.0,5.0
26,4ODNGNJKKP,110,7.717957e+05,8.536988e+03,-1.358133e+04,2.143173e+04,110,15,38,0,1,11,4,1,1,7,0,1,10,11,6,0,5,1,0,4,9,Firm C,NaN,I,1.0,3.0
27,4R2CINXSWI,11,1.006693e+05,1.206077e+04,-1.206077e+04,1.635642e+04,11,6,4,0,0,0,0,0,1,2,0,0,0,0,1,1,0,2,0,0,0,Firm G,YES,I,1.0,5.0
28,59YB0GWAEV,61,3.536468e+05,8.793244e+03,-1.213252e+04,1.947788e+04,61,13,19,0,0,3,1,1,2,7,0,0,0,2,2,1,0,5,5,2,11,NaN,NaN,P,10.0,0.0
29,5EEVEQ6ENR,103,6.307095e+05,8.273836e+03,-1.754850e+04,1.845136e+04,103,17,27,2,1,4,4,2,7,12,1,0,1,2,12,1,3,12,0,1,11,NaN,NaN,P,10.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,SKBPNEDBQS,2,5.330643e+03,2.665321e+03,1.100110e+03,4.230532e+03,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,Firm J,NaN,I,1.0,9.0
121,SXS9F6CSY1,92,5.370178e+06,5.963624e+04,3.993186e+04,8.775526e+04,92,14,39,0,0,1,2,0,5,4,0,1,0,9,9,4,1,3,1,3,10,Firm L,YES,I,1.0,4.0
122,T8NOPQSIWF,81,5.744810e+05,1.059173e+04,-1.656356e+04,1.790336e+04,81,14,24,0,0,7,3,0,2,5,0,0,1,9,4,4,4,6,6,4,2,NaN,NaN,P,20.0,0.0
123,T9AD15KSTV,36,3.055455e+06,9.015533e+04,-1.695426e+05,3.198018e+05,36,11,15,0,0,0,0,3,2,0,0,1,0,1,1,2,2,3,1,0,5,NaN,NaN,P,2.0,0.0
124,TMD4NCAUKL,87,5.228629e+06,6.032612e+04,3.238509e+04,8.542272e+04,87,15,28,0,0,6,4,3,5,4,0,0,4,3,5,4,2,6,2,6,5,Firm H,NaN,I,1.0,6.0
125,TN2QK2P9RS,86,5.234439e+05,8.320914e+03,-1.810226e+04,1.810226e+04,86,15,42,1,0,2,3,1,2,3,0,0,3,3,0,3,2,9,3,5,4,NaN,NaN,P,2.0,0.0
126,TPJKXTM0CB,94,5.735273e+06,6.111584e+04,3.063829e+04,8.674390e+04,94,15,33,0,1,6,2,9,2,2,0,0,4,5,3,4,5,4,0,5,9,Firm C,NaN,I,1.0,9.0
127,TXW929QG7V,78,9.182620e+06,1.040192e+05,-9.328456e+04,3.241065e+05,78,16,26,0,1,8,3,0,3,7,1,2,1,2,6,2,3,6,0,2,5,Firm A,NaN,I,1.0,8.0
128,U3TBS57JJ5,75,6.216003e+05,9.553494e+03,-1.618676e+04,1.981929e+04,75,13,29,0,0,4,4,0,4,5,0,0,3,2,6,3,7,1,0,2,5,NaN,NaN,P,16.0,0.0
129,U7BJKAE83O,127,8.181966e+05,8.490448e+03,-2.097187e+04,2.378837e+04,127,17,43,1,4,10,5,4,3,12,0,0,1,5,7,9,8,4,1,7,3,NaN,NaN,P,20.0,0.0
130,U9EL7D4ERT,63,6.208968e+06,1.012678e+05,-1.079624e+05,3.507030e+05,63,16,21,0,1,6,3,1,1,5,1,0,2,0,2,1,2,6,2,3,6,Firm E,NaN,I,1.0,7.0
131,UBRJS7UAWJ,23,1.402139e+05,8.700484e+03,-9.252408e+03,1.903244e+04,23,6,12,0,0,2,0,0,0,5,0,0,0,0,0,1,0,0,0,1,2,Firm A,NaN,I,1.0,6.0
132,UDSS4B9P65,50,3.763765e+05,8.961791e+03,-1.712210e+04,1.968042e+04,50,13,22,1,0,1,1,0,3,6,1,0,0,1,3,7,1,0,0,1,2,Firm G,YES,I,1.0,8.0
133,UI7EJIY2KI,59,4.805855e+05,1.006840e+04,-1.595735e+04,2.029554e+04,59,13,26,0,0,9,2,1,3,5,0,0,0,1,3,1,0,3,1,2,2,Firm C,NaN,I,1.0,5.0
134,UYPHDND4FA,96,7.508321e+05,8.030090e+03,-2.192644e+04,2.814602e+04,96,17,33,4,1,7,2,3,0,10,0,4,3,4,5,1,1,4,4,5,5,Firm B,NaN,I,1.0,7.0
135,V9N3ZKPZHH,115,7.213861e+05,8.092905e+03,-1.675618e+04,2.524663e+04,115,16,38,0,0,4,3,3,5,13,0,1,1,13,10,2,1,6,4,5,6,NaN,NaN,P,20.0,0.0
136,W1Y175DVPO,136,9.479605e+05,8.084038e+03,-1.930648e+04,2.584896e+04,136,16,37,0,0,16,4,5,9,16,0,6,5,2,4,8,1,7,1,8,7,Firm B,NaN,I,1.0,5.0
137,W5S4X42JSQ,28,2.265147e+06,1.245614e+05,-2.121294e+05,2.538099e+05,28,11,9,0,0,2,3,0,1,0,0,0,0,1,3,3,2,1,0,2,1,Firm A,NaN,I,1.0,5.0
138,WCEPX3NJVK,93,5.545930e+05,8.210382e+03,-1.686463e+04,2.192668e+04,93,14,36,0,0,2,18,3,3,4,0,0,0,8,3,2,4,1,3,2,4,NaN,NaN,P,16.0,0.0
139,WL69WBRD1G,8,2.848942e+04,5.623535e+03,-8.919191e+03,8.919191e+03,8,4,0,0,1,0,0,0,0,3,0,0,0,0,0,0,0,0,0,3,1,Firm H,NaN,I,1.0,3.0
140,X7SUJHX95Z,106,6.660170e+05,8.706083e+03,-2.032130e+04,2.087157e+04,106,15,45,0,1,4,7,1,4,5,0,0,6,11,5,5,5,3,0,3,1,Firm J,NaN,I,1.0,3.0
141,XJZM8GRCHE,51,3.744877e+05,6.507420e+03,-1.758230e+04,2.196842e+04,51,12,28,0,0,0,2,2,1,1,0,1,0,3,1,6,2,0,2,0,2,Firm L,YES,I,1.0,6.0
142,YH7NSGYL1V,8,8.340532e+04,9.717625e+03,9.478509e+02,1.909088e+04,8,4,4,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,2,0,Firm F,NaN,I,1.0,6.0
143,Z3X0LBABH7,85,5.560716e+05,7.762285e+03,-2.040241e+04,2.040241e+04,85,13,26,0,0,8,4,0,6,11,0,0,2,3,9,4,0,5,1,2,4,Firm K,NaN,I,1.0,8.0
144,ZDOIN2X3US,3,3.995752e+04,1.499310e+04,6.559881e+03,1.840454e+04,3,3,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,Firm G,YES,I,1.0,3.0
145,ZEKBKU4CMP,18,2.719290e+08,1.513075e+07,1.386975e+07,1.616797e+07,18,9,8,0,0,0,0,1,1,1,0,1,0,0,0,1,1,1,0,0,3,Firm J,NaN,I,1.0,5.0
146,ZK6QSE5CWV,50,5.567233e+06,9.836275e+04,-9.971182e+04,3.941943e+05,50,14,22,0,0,3,4,2,1,2,0,1,1,2,4,3,0,3,1,0,1,Firm G,YES,I,1.0,6.0
147,ZKMO6UT86Q,59,4.088681e+05,8.780690e+03,-1.555391e+04,2.107526e+04,59,10,15,0,0,4,0,0,5,6,0,0,0,3,10,0,4,2,0,3,7,Firm J,NaN,I,1.0,6.0
148,ZQ5C5X1DWI,64,4.000037e+05,1.025166e+04,-1.772044e+04,2.160109e+04,64,15,10,0,0,1,1,5,1,6,0,1,0,12,5,8,2,4,1,1,6,NaN,NaN,P,2.0,0.0
149,ZW0J9NZAS3,109,7.367313e+05,8.137451e+03,-1.667514e+04,2.214264e+04,109,16,37,3,0,3,2,1,2,15,0,0,2,3,11,8,4,8,1,2,7,NaN,NaN,P,2.0,0.0

In [27]:
df_merged_all2.to_csv(r"fin.csv")